[package]
name = "canadensis"
version = "0.1.0"
authors = ["Sam Crow <scrow@eng.ucsd.edu>"]
edition = "2018"
keywords = ["embedded", "uavcan", "uav", "can"]
categories = ["embedded", "no-std"]
documentation = "https://docs.rs/canadensis"
repository = "https://github.com/samcrow/canadensis"
license = "MIT OR Apache-2.0"
description = "A UAVCAN v1.0 implementation: Node types and re-exports from other canadensis crates"

[dependencies]
fallible_collections = "0.1.2"
hash32 = "0.2.1"
heapless = "0.7.0"
half = "1.7.1"
log = "0.4"

# Depend on all the other canadensis crates, except canadensis_data_types and the less-commonly-used ones
[dependencies.canadensis_can]
version = "0.1.0"
path = "../canadensis_can"
[dependencies.canadensis_core]
version = "0.1.0"
path = "../canadensis_core"
[dependencies.canadensis_derive_register_block]
version = "0.1.0"
path = "../canadensis_derive_register_block"
[dependencies.canadensis_encoding]
version = "0.1.0"
path = "../canadensis_encoding"
[dependencies.canadensis_filter_config]
version = "0.1.0"
path = "../canadensis_filter_config"
# Less-commonly-used canadensis crates:
# * canadensis_bxcan
# * canadensis_crc
# * canadensis_filter_config
# * canadensis_linux
# * canadensis_pnp_client
# * canadensis_write_crc


# canadensis_data_types is likely to change more frequently. Because of the Heartbeat and NodeInfo types, this is still
# a public dependency.
[dependencies.canadensis_data_types]
version = "0.1.0"
path = "../canadensis_data_types"

[dev-dependencies]
socketcan = "1.7.0"
rand = "0.7.3"

[dev-dependencies.canadensis_linux]
version = "0.1.0"
path = "../canadensis_linux"
