[package]
name = "canadensis_codegen_rust"
version = "0.1.0"
edition = "2018"
description = "Generates Rust code for data types based on DSDL files"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heck = "0.3.3"

[dependencies.canadensis_dsdl_frontend]
path = "../canadensis_dsdl_frontend"
[dependencies.canadensis_bit_length_set]
path = "../canadensis_bit_length_set"
