[package]
name = "canadensis_encoding"
version = "0.1.0"
authors = ["Sam Crow <scrow@eng.ucsd.edu>"]
edition = "2018"
keywords = ["embedded", "uavcan", "uav", "can"]
categories = ["embedded", "no-std"]
repository = "https://github.com/samcrow/canadensis"
license = "MIT OR Apache-2.0"
description = "A UAVCAN v1 implementation: Transfer encoding and decoding"

[dependencies]
half = "1.7.1"

[dev-dependencies]
heapless = "0.7.0"
