[package]
name = "prdt_compile_test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
half = "1.7.1"
heapless = "0.7.7"
